# Generated by Django 5.2.1 on 2025-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_uygulama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vat_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Toplam KDV Tutarı'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Faturaya uygulanacak KDV oranı (örneğin %18 için 18.00 girin)', max_digits=5, verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Toplam Tutar (KDV Dahil)'),
        ),
    ]
