# Generated by Django 5.2.1 on 2025-06-15 16:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_uygulama', '0003_alter_invoice_options_remove_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_holder_name',
            new_name='account_owner_name',
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('carrier', 'iban')},
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='tax_office',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_license_document',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_expiry_date',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='driving_license_image',
            field=models.FileField(blank=True, null=True, upload_to='carrier_documents/driving_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Ehliyet Görseli'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ehliyet Numarası'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='identity_document_image',
            field=models.FileField(blank=True, null=True, upload_to='carrier_documents/identity_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Kimlik Belgesi Görseli'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='identity_document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kimlik Belgesi Numarası'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='identity_document_type',
            field=models.CharField(choices=[('TCKN', 'T.C. Kimlik Numarası'), ('VERGI_NO', 'Vergi Kimlik Numarası'), ('PASAPORT', 'Pasaport Numarası')], default='TCKN', max_length=10, verbose_name='Kimlik Belgesi Tipi'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ehliyet Geçerlilik Tarihi'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Net Tutar (KDV Hariç)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_date_earliest',
            field=models.DateField(blank=True, null=True, verbose_name='En Erken Teslimat Tarihi'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_date_latest',
            field=models.DateField(blank=True, null=True, verbose_name='En Geç Teslimat Tarihi'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hacim (m³)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ağırlık (kg)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kapasite (m³)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kapasite (Ton)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/inspections/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Muayene Belgesi (PDF/Resim)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate_image',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/plate_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Plaka Görseli'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_license_image',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/vehicle_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Araç Ruhsat Görseli'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CEKICI', 'Çekici'), ('DORSE', 'Dorse'), ('KAMYON', 'Kamyon'), ('KAMYONET', 'Kamyonet'), ('MUTEAHHIT', 'Müteahhit (İş Makinesi)'), ('DIGER', 'Diğer')], default='KAMYON', max_length=20, verbose_name='Araç Tipi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ana_uygulama.company', verbose_name='Bağlı Olduğu Firma'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to='ana_uygulama.vehicle', verbose_name='Atanan Araç'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cost_for_shipper',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nakliyeciye Maliyet (Taşıyıcıya Ödenen) (TL)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price_for_factory',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fabrikaya Kesilecek Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quote_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment', to='ana_uygulama.quoterequest', verbose_name='İlişkili Fiyat Teklifi'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING_ASSIGNMENT', 'Atama Bekliyor'), ('ASSIGNED', 'Taşıyıcıya Atandı'), ('IN_TRANSIT', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('BILLED', 'Faturalandırıldı'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='PENDING_ASSIGNMENT', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sürücü Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sürücü Telefonu'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/insurances/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Sigorta Poliçesi (PDF/Resim)'),
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch_name',
        ),
    ]
