# Generated by Django 5.2.1 on 2025-06-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_uygulama', '0004_rename_account_holder_name_bankaccount_account_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('INCOMING', 'Gelen Ödeme (Tahsilat)'), ('OUTGOING', 'Giden Ödeme (Ödeme)')], max_length=10, verbose_name='Ödeme Yönü'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ana_uygulama.shipment', verbose_name='İlişkili Sevkiyat'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shipper_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_shipper', to='ana_uygulama.company', verbose_name='Nakliyeci Firma'),
        ),
    ]
