# Generated by Django 5.2.1 on 2025-06-28 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_uygulama', '0005_alter_payment_options_alter_payment_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate_image',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/plate_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Sürücü Belgesi Görseli'),
        ),
    ]
