# Generated by Django 5.2.1 on 2025-06-29 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_uygulama', '0007_alter_invoice_status'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INVOICE_CREATED', 'Fatura Oluşturuldu'), ('PAYMENT_RECEIVED', 'Ödeme Alındı'), ('VEHICLE_ADDED', 'Araç Eklendi'), ('BID_SUBMITTED', 'Teklif Verildi'), ('SHIPMENT_COMPLETED', 'Sevkiyat Tamamlandı')], max_length=50, verbose_name='Eylem Türü')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Profili')),
            ],
            options={
                'verbose_name': 'Aktivite Kaydı',
                'verbose_name_plural': 'Aktivite Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
