# Generated by Django 5.2.1 on 2025-06-29 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_uygulama', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Yakıt'), ('MAINTENANCE', 'Bakım & Onarım'), ('SALARY', 'Maaş'), ('TAX', 'Vergi & Harç'), ('OTHER', 'Diğer')], default='OTHER', max_length=20, verbose_name='Kategori')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (TL)')),
                ('expense_date', models.DateField(verbose_name='Gider Tarihi')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Profili')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-expense_date'],
            },
        ),
    ]
